### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by Jestyak2009** [GermantovA/Erida#8]
Delete this

**Comment by ThomasThings** [comment]
they're fixing it just give them a minute to do it

**Comment by GermantovA** [comment]
I can't do it so fast. My time is 0:57. I will start doing it in 7:30

**Comment by Froomeeth** [comment]
mfw
![a](https://user-images.githubusercontent.com/116809073/211174293-12ca53a0-21ab-4e1f-aceb-d8592b53f1aa.jpg)

**Comment by ThomasThings** [comment]
wait you can post images in the github comments?

Glorious.

**Comment by ThomasThings** [comment]
also why am I getting emails about it lol
