### ISSUE TITLE
вам нужна помощь с проблемой отсутствия текстуры у бура 1х1 на одной из лун?

### ISSUE THREAD

**Issue by Zhiltsov-Arseny** [GermantovA/Erida#9]

**Comment by GermantovA** [comment]
Привет, да это было бы хорошо

**Comment by GermantovA** [comment]
Можете помочь решить проблему? Iron furnace не отображается на dysnomy.

**Comment by Zhiltsov-Arseny** [comment]
короче нам потребуется спрайт размером 32 на 32 с белой точкой посередине (того размера которая тебе нужна) затем переминовываем спрайт  на название бура потом тире а после него пишем item-1

**Comment by Shvabrik** [comment]
У меня вопрос, почему не открывается и не иследуется новый контент на одной из лун?

**Comment by GermantovA** [comment]
Я пытался исправить это, но не выходит, попытаюсь исправить это завтра.

**Comment by GermantovA** [comment]
Так посмотрел, всё исследуется но НИКАКИЕ фабрики не показываются

**Comment by Shvabrik** [comment]
ладно
